/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Control;
import Models.Card;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author hanna
 */
public class BlackJackView3 extends javax.swing.JFrame {

    /**
     * Creates new form BlackJackView3
     */
    private int  sum=0 ;
    private int HIT =0;
    private Card[] c = new Card[5];
    
    public BlackJackView3()
    {
       // 
        
        initComponents();
        jLabel1.setIcon(new javax.swing.ImageIcon("src\\AllCards\\newblackjack.jpg"));
        jLabel11.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
         jButton3.setVisible(false);
         jButton5.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel12.setVisible(false);
         jLabel13.setVisible(false);
         jLabel10.setVisible(false);
         jTextField1.setVisible(false);
         jTextField2.setVisible(false);
         jTextField3.setVisible(false);
         jTextField4.setVisible(false);
         jTextField6.setVisible(false);
         jTextField5.setVisible(false);
       
        
         
         
           
    }
 
 
    public JLabel GetButton()
    {
        return this.jLabel5;
    }
    public JLabel GetButton4()
    {
        return this.jLabel4;
    }
     public JLabel GetButton6()
    {
        return this.jLabel6;
    }
      public JLabel GetButton7()
    {
        return this.jLabel7;
    }
      public JTextField GetText1()
      {
          return this.jTextField1 ;
      }
        public JTextField GetText2()
      {
          return this.jTextField2 ;
      }
          public JTextField GetText3()
      {
          return this.jTextField3 ;
      }
            public JTextField GetText4()
      {
          return this.jTextField4 ;
      }
       public JTextField GetText5()
       {
                 return this.jTextField5 ;
       }
               public JTextField GetText6()
            {
                 return this.jTextField6 ;
            }
               public JLabel GetLabel10()
               {
                   return this.jLabel10 ; 
               }
               public JLabel GetLabel11()
               {
                   return this.jLabel11;
               }
       public JLabel GetLabel12()
       {
           return this.jLabel12 ;
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 400, 150, 60);

        jButton2.setText("Sand");
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 400, 150, 60);

        jButton1.setText("Hit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 400, 150, 60);

        jButton5.setText("Deal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(300, 60, 130, 23);

        jLabel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 30, 90, 100);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 30, 90, 100);

        jButton4.setText("New Game");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(310, 20, 110, 23);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Player ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 110, 20);

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Dealer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 10, 120, 30);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 30, 90, 110);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 40, 100, 90);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(570, 30, 90, 110);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 260, 60, 30);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(70, 260, 59, 30);

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(470, 250, 59, 20);

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(640, 250, 59, 20);

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(120, 300, 59, 30);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("SumP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 290, 70, 40);

        jTextField6.setText("jTextField6");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(470, 300, 59, 30);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("SumD");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(574, 294, 60, 30);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 30, 80, 100);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 130, 80, 100);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(110, 130, 70, 80);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setVisible(false);
        jButton5.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    public void getSum(int sumP)
    {
        this.sum = sumP ;
    }
      public void getCard(Card cPlayer[])
    {
        for(int i=0; i<5 ; i++)
        this.c[i] = cPlayer[i] ;
        //this.sum = this.c[0].getValue()+c[1].getValue();
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField5.setVisible(true);
       
       jLabel5.setVisible(true);
       jLabel4.setVisible(true);   
       jLabel6.setVisible(true);
       jLabel7.setVisible(true);
       jLabel10.setVisible(true);
   
       jButton5.setVisible(false); 
       jButton1.setVisible(true);
       jButton2.setVisible(true);
       jButton3.setVisible(true);
       
       if(this.sum == 21)
       {
          JOptionPane.showMessageDialog(null, "You Got BlackJack");

       }
      
    
      
        
    }//GEN-LAST:event_jButton5ActionPerformed

 
    
  
          
    private void jLabel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel5AncestorAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel5AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   
      
       
       this.HIT ++;
       switch(this.HIT)
       {
           case 1:  this.jLabel11.setVisible(true); break;
           case 2:  this.jLabel12.setVisible(true); break;
           case 3: this.jLabel13.setVisible(true); break;
              
       }
       
      
           this.sum += this.c[this.HIT + 1].getValue() ;
           this.jTextField5.setText(""+this.sum);
           
    
       if(this.sum>21)
       {
           JOptionPane.showMessageDialog(null, "busted");
           jButton1.setVisible(false);
           this.jLabel10.setVisible(false);
           this.jTextField6.setVisible(true);
        
       }
      
     
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackView3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
